### ISSUE TITLE
DuckDB connections should reflect correctly on UI

### ISSUE THREAD

**Issue by sunank200** [astronomer/airflow-provider-duckdb#7]
The DuckDB connection configured in airflow_settings.yaml is created on the UI, but its custom File field comes up blank - even when set in the Host field as shown in [ci-test-connections.yaml](https://github.com/astronomer/astro-sdk/blob/fe2bbe3db8cfd41664f7251a6169b84a8f699390/.github/ci-test-connections.yaml#L129-L131). I had to set it with an env var os.environ['AIRFLOW_CONN_DUCKDB_CONN'] = 'duckdb://%2Ftmp%2Fdb.duckdb'

Unless I’m configuring airflow_settings.yaml wrong, the 1st item should be addressed on the [Hook’s UI field behavior](https://github.com/astronomer/airflow-provider-duckdb/blob/main/duckdb_provider/hooks/duckdb_hook.py#L50-L57).

**Comment by josh-fell** [comment]
Setting up `airflow_settings.yaml` in a local Astro project like this worked for me:
```yaml
airflow:
  connections:
    - conn_id: duckdb
      conn_type: duckdb
      conn_host: duckdb://%2Ftmp%2Fdb.duckdb
```
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/48934154/221741421-167f774f-3bb6-492f-9f57-cae227867437.png">
